sudo: required
dist: trusty
language: python
python:
  - '2.7'
install:
  - pip install --quiet -r ci/requirements.txt
  - git clone https://github.com/"${TRAVIS_REPO_SLUG%%/*}"/qubes-builder ~/qubes-builder
# debootstrap in trusty is old...
before_script: sudo ln -s sid /usr/share/debootstrap/scripts/stretch
script:
  - PYTHONPATH=test-packages pylint --rcfile=ci/pylintrc qubes
  - ./run-tests --no-syslog
  - ~/qubes-builder/scripts/travis-build
env:
 - DIST_DOM0=fc23 USE_QUBES_REPO_VERSION=3.2 USE_QUBES_REPO_TESTING=1

deploy:
  provider: script
  script: ~/qubes-builder/scripts/travis-deploy
  on:
    branch:
      - core3-devel-staging

addons:
  apt:
    packages:
      - debootstrap

# vim: ts=2 sts=2 sw=2 et
